// app/layout.tsx
import "@/css/satoshi.css";
import "@/css/style.css";
import { Providers } from "../../providers"; // your Redux / Theme providers etc.

export const metadata = {
  title: "Magson",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
